#!/usr/bin/env python3
"""Generate DXGI POD layouts and independent SDK sizeof/offsetof checks.
The schema names native fields. The C++ test measures the actual Windows SDK
structs rather than constructing a duplicate of the BlitzMax declarations.
"""
from pathlib import Path
root=Path(__file__).resolve().parent.parent
# (BlitzMax name, native name, [(field, BlitzMax type, optional array length)])
layouts=[]
def add(name, fields, native=None):
    layouts.append((name,native or name,[tuple(f.split(':')) for f in fields.split()]))
add('DXGI_LUID','LowPart:UInt HighPart:Int','LUID')
add('DXGI_RECT','left:Int top:Int right:Int bottom:Int','RECT')
add('DXGI_POINT','x:Int y:Int','POINT')
add('DXGI_RATIONAL','Numerator:UInt Denominator:UInt')
add('DXGI_SAMPLE_DESC','Count:UInt Quality:UInt')
add('DXGI_RGB','Red:Float Green:Float Blue:Float')
add('DXGI_RGBA','r:Float g:Float b:Float a:Float')
add('DXGI_MODE_DESC','Width:UInt Height:UInt RefreshRate:DXGI_RATIONAL Format:Int ScanlineOrdering:Int Scaling:Int')
add('DXGI_SURFACE_DESC','Width:UInt Height:UInt Format:Int SampleDesc:DXGI_SAMPLE_DESC')
add('DXGI_MAPPED_RECT','Pitch:Int pBits:Byte_Ptr')
add('DXGI_OUTPUT_DESC','DeviceName:Short:32 DesktopCoordinates:DXGI_RECT AttachedToDesktop:Int Rotation:Int Monitor:Byte_Ptr')
add('DXGI_FRAME_STATISTICS','PresentCount:UInt PresentRefreshCount:UInt SyncRefreshCount:UInt SyncQPCTime:Long SyncGPUTime:Long')
adapter='Description:Short:128 VendorId:UInt DeviceId:UInt SubSysId:UInt Revision:UInt DedicatedVideoMemory:Size_T DedicatedSystemMemory:Size_T SharedSystemMemory:Size_T AdapterLuid:DXGI_LUID'
add('DXGI_ADAPTER_DESC',adapter)
add('DXGI_ADAPTER_DESC1',adapter+' Flags:UInt')
add('DXGI_SWAP_CHAIN_DESC','BufferDesc:DXGI_MODE_DESC SampleDesc:DXGI_SAMPLE_DESC BufferUsage:UInt BufferCount:UInt OutputWindow:Byte_Ptr Windowed:Int SwapEffect:Int Flags:UInt')
add('DXGI_SHARED_RESOURCE','Handle:Byte_Ptr')
add('DXGI_GAMMA_CONTROL_CAPABILITIES','ScaleAndOffsetSupported:Int MaxConvertedValue:Float MinConvertedValue:Float NumGammaControlPoints:UInt ControlPointPositions:Float:1025')
add('DXGI_GAMMA_CONTROL','Scale:DXGI_RGB Offset:DXGI_RGB GammaCurve:DXGI_RGB:1025')
add('DXGI_SWAP_CHAIN_DESC1','Width:UInt Height:UInt Format:Int Stereo:Int SampleDesc:DXGI_SAMPLE_DESC BufferUsage:UInt BufferCount:UInt Scaling:Int SwapEffect:Int AlphaMode:Int Flags:UInt')
add('DXGI_SWAP_CHAIN_FULLSCREEN_DESC','RefreshRate:DXGI_RATIONAL ScanlineOrdering:Int Scaling:Int Windowed:Int')
add('DXGI_PRESENT_PARAMETERS','DirtyRectsCount:UInt pDirtyRects:DXGI_RECT_Ptr pScrollRect:DXGI_RECT_Ptr pScrollOffset:DXGI_POINT_Ptr')

b=['\' Generated by tools/generate_layouts.py. BOOL/HRESULT are 32-bit Int; handles are pointers.', 'SuperStrict','','Import Pub.Win32','']
c=['// Generated native Windows SDK layout oracle.','#include <dxgi1_2.h>','#include <cstddef>', 'extern "C" int dxgi_test_layout(int type,int field) {',' switch(type) {']
t=['SuperStrict','Framework BRL.StandardIO','Import Pub.DXGI','Import "layouts.cpp"','','Extern "C"',' Function dxgi_test_layout:Int(kind:Int,field:Int)','End Extern','','Function Check(ok:Int,message:String)',' If Not ok Then Throw "DXGI layout mismatch: "+message','End Function','','Try']
checks=0
for i,(name,native,fields) in enumerate(layouts):
    b.append('Struct '+name)
    c += [f' case {i}: switch(field) {{',f'  case -1: return sizeof({native});']
    t += [f' Local s{i}:{name}',f' Check(SizeOf(s{i})=dxgi_test_layout({i},-1),"sizeof {name}")']
    checks+=1
    for j,f in enumerate(fields):
        field,kind=f[:2]
        kind=kind.replace('_Ptr',' Ptr')
        count=int(f[2]) if len(f)>2 else None
        b.append('\tField '+('StaticArray ' if count else '')+field+':'+kind+(f'[{count}]' if count else ''))
        c.append(f'  case {j}: return offsetof({native},{field});')
        target=f's{i}.{field}'+('[0]' if count else '')
        t.append(f' Check(Byte Ptr(Varptr {target})-Byte Ptr(Varptr s{i})=dxgi_test_layout({i},{j}),"offsetof {name}.{field}")')
        checks+=1
    b.append('End Struct\n')
    c.append(' } break;')
c+=[' }',' return -1;','}']
t += [f' Print "Pub.DXGI: {checks} native layout checks passed"','Catch error:Object',' Print "FAILED: "+error.ToString()',' EndWithCode(1)','End Try']
(root/'common.bmx').write_text('\n'.join(b).rstrip()+'\n')
(root/'tests/layouts.cpp').write_text('\n'.join(c)+'\n')
(root/'tests/layouts.bmx').write_text('\n'.join(t)+'\n')
print(f'Generated {len(layouts)} structures and {checks} SDK layout checks')
