#!/usr/bin/env python3
"""Regenerate the selected DXGI interfaces/constants from MinGW-w64 SDK headers.
Usage: python3 tools/generate_bindings.py /path/to/mingw/include
The generated files are checked in; building the module does not run Python.
Unknown signatures are errors, never guessed or replaced by empty vtable slots.
"""
from pathlib import Path
import re
import sys

sdk = Path(sys.argv[1])
module = Path(__file__).resolve().parent.parent
headers = {n: (sdk / n).read_text() for n in
           ['dxgi.h', 'dxgi1_2.h', 'dxgi1_3.h', 'dxgitype.h', 'dxgiformat.h', 'dxgicommon.h', 'winerror.h']}
interfaces = ['IDXGIObject', 'IDXGIDeviceSubObject', 'IDXGIResource', 'IDXGISurface',
              'IDXGISurface1', 'IDXGIOutput', 'IDXGIAdapter', 'IDXGISwapChain',
              'IDXGIFactory', 'IDXGIDevice', 'IDXGIAdapter1', 'IDXGIDevice1',
              'IDXGIFactory1', 'IDXGISwapChain1', 'IDXGIFactory2']
scalar = {'HRESULT': 'Int', 'WINBOOL': 'Int', 'UINT': 'UInt', 'DWORD': 'UInt',
          'INT': 'Int', 'void': 'Void', 'DXGI_USAGE': 'UInt',
          'DXGI_FORMAT': 'Int', 'DXGI_RESIDENCY': 'Int', 'DXGI_MODE_ROTATION': 'Int',
          'LARGE_INTEGER': 'Long', 'LUID': 'DXGI_LUID', 'RECT': 'DXGI_RECT'}
handles = {'HANDLE', 'HWND', 'HDC', 'HMODULE'}

def map_type(t, method='', parameter=''):
    t = re.sub(r'\bconst\b', '', t).replace(' ', '')
    depth = t.count('*')
    base = t.replace('*', '')
    if base in ('REFIID', 'REFGUID') and not depth:
        return 'Byte Ptr'
    if base in handles:
        return 'Byte Ptr' + ' Ptr' * depth
    if base == 'void' and depth:
        return 'Byte' + ' Ptr' * depth
    if base == 'IUnknown' or base in interfaces:
        b = 'IUnknown_' if base == 'IUnknown' else base
        if depth == 1:
            return b
        if depth == 2:
            # These two methods accept/return arrays of interface pointers.
            return b + (' Ptr' if method in ('QueryResourceResidency', 'CreateSurface') else ' Var')
        raise ValueError(t)
    if base in scalar:
        return scalar[base] + ' Ptr' * depth
    if base.startswith('DXGI_') and depth == 1:
        return base + ' Ptr'
    raise ValueError((t, method, parameter))

out = ["' Generated by tools/generate_bindings.py; complete vtable order from SDK headers.",
       'SuperStrict', '', 'Import "common.bmx"', '', 'Extern "Win32"']
all_headers = '\n'.join(headers.values())
for name in interfaces:
    match = re.search(r'\n' + name + r' : public (\w+)\s*\{(.*?)\n\};', all_headers, re.S)
    if not match:
        raise ValueError(name)
    parent, body = match.groups()
    out.append('\nInterface ' + name + ' Extends ' + ('IUnknown_' if parent == 'IUnknown' else parent))
    methods = re.findall(r'virtual (\w+) STDMETHODCALLTYPE (\w+)\(\s*(.*?)\) = 0;', body, re.S)
    assert len(methods) == body.count('virtual '), name
    for ret, method, args in methods:
        params = []
        for arg in args.split(',') if args.strip() else []:
            am = re.fullmatch(r'\s*(.*?)\b(\w+)\s*', arg, re.S)
            native_type, param = am.groups()
            params.append('p_' + param + ':' + map_type(native_type, method, param))
        out.append('\tMethod ' + method + ('' if ret == 'void' else ':' + map_type(ret)) + '(' + ', '.join(params) + ')')
    out.append('End Interface')
out.append('\nEnd Extern\n')
(module / 'interfaces.bmx').write_text('\n'.join(out))

# Enum values and numeric DXGI macros, including HRESULTs from winerror.h.
values = {}
for source in headers.values():
    for name, value in re.findall(r'\b(DXGI_\w+)\s*=\s*(0x[0-9a-fA-F]+|\d+)\b', source):
        values[name] = (value, 'UInt' if int(value, 0) > 0x7fffffff else 'Int')
    for name, expr in re.findall(r'^#define (DXGI_\w+)\s+([^\n]+)', source, re.M):
        m = re.fullmatch(r'\s*(?:_HRESULT_TYPEDEF_|__MSABI_LONG)?\(?(0x[0-9a-fA-F]+|\d+)[UuLl]*\)?\s*', expr)
        if m:
            values[name] = (m[1], 'Int' if name.startswith(('DXGI_ERROR_', 'DXGI_STATUS_')) else 'UInt')
lines = ["' Generated DXGI constants; availability depends on the runtime interface version.", 'SuperStrict', '']
for name, (value, kind) in sorted(values.items()):
    lines.append(f'Const {name}:{kind}=' + ('$' + value[2:] if value.lower().startswith('0x') else value))
(module / 'constants.bmx').write_text('\n'.join(lines) + '\n')
(module / 'iids.bmx').write_text("' Generated immutable SDK IID addresses; do not modify or free them.\nSuperStrict\n\nImport \"iids.cpp\"\n\nExtern \"C\"\n\tFunction bmx_dxgi_iid:Byte Ptr(index:Int)\nEnd Extern\n\n" + '\n'.join(f'Global IID_{name}:Byte Ptr=bmx_dxgi_iid({n})' for n, name in enumerate(interfaces)) + '\n')
(module / 'iids.cpp').write_text('// Generated from the selected DXGI interface list.\n#include <dxgi1_2.h>\nextern "C" const void *bmx_dxgi_iid(int index) {\n static const GUID *const ids[] = {\n' + ',\n'.join('  &__uuidof(' + n + ')' for n in interfaces) + '\n };\n return index>=0 && index<int(sizeof(ids)/sizeof(ids[0])) ? ids[index] : nullptr;\n}\n')
print(f'Generated {len(interfaces)} complete interfaces and {len(values)} constants')
