' Generated by tools/generate_layouts.py. BOOL/HRESULT are 32-bit Int; handles are pointers.
SuperStrict

Import Pub.Win32

Struct DXGI_LUID
	Field LowPart:UInt
	Field HighPart:Int
End Struct

Struct DXGI_RECT
	Field left:Int
	Field top:Int
	Field right:Int
	Field bottom:Int
End Struct

Struct DXGI_POINT
	Field x:Int
	Field y:Int
End Struct

Struct DXGI_RATIONAL
	Field Numerator:UInt
	Field Denominator:UInt
End Struct

Struct DXGI_SAMPLE_DESC
	Field Count:UInt
	Field Quality:UInt
End Struct

Struct DXGI_RGB
	Field Red:Float
	Field Green:Float
	Field Blue:Float
End Struct

Struct DXGI_RGBA
	Field r:Float
	Field g:Float
	Field b:Float
	Field a:Float
End Struct

Struct DXGI_MODE_DESC
	Field Width:UInt
	Field Height:UInt
	Field RefreshRate:DXGI_RATIONAL
	Field Format:Int
	Field ScanlineOrdering:Int
	Field Scaling:Int
End Struct

Struct DXGI_SURFACE_DESC
	Field Width:UInt
	Field Height:UInt
	Field Format:Int
	Field SampleDesc:DXGI_SAMPLE_DESC
End Struct

Struct DXGI_MAPPED_RECT
	Field Pitch:Int
	Field pBits:Byte Ptr
End Struct

Struct DXGI_OUTPUT_DESC
	Field StaticArray DeviceName:Short[32]
	Field DesktopCoordinates:DXGI_RECT
	Field AttachedToDesktop:Int
	Field Rotation:Int
	Field Monitor:Byte Ptr
End Struct

Struct DXGI_FRAME_STATISTICS
	Field PresentCount:UInt
	Field PresentRefreshCount:UInt
	Field SyncRefreshCount:UInt
	Field SyncQPCTime:Long
	Field SyncGPUTime:Long
End Struct

Struct DXGI_ADAPTER_DESC
	Field StaticArray Description:Short[128]
	Field VendorId:UInt
	Field DeviceId:UInt
	Field SubSysId:UInt
	Field Revision:UInt
	Field DedicatedVideoMemory:Size_T
	Field DedicatedSystemMemory:Size_T
	Field SharedSystemMemory:Size_T
	Field AdapterLuid:DXGI_LUID
End Struct

Struct DXGI_ADAPTER_DESC1
	Field StaticArray Description:Short[128]
	Field VendorId:UInt
	Field DeviceId:UInt
	Field SubSysId:UInt
	Field Revision:UInt
	Field DedicatedVideoMemory:Size_T
	Field DedicatedSystemMemory:Size_T
	Field SharedSystemMemory:Size_T
	Field AdapterLuid:DXGI_LUID
	Field Flags:UInt
End Struct

Struct DXGI_SWAP_CHAIN_DESC
	Field BufferDesc:DXGI_MODE_DESC
	Field SampleDesc:DXGI_SAMPLE_DESC
	Field BufferUsage:UInt
	Field BufferCount:UInt
	Field OutputWindow:Byte Ptr
	Field Windowed:Int
	Field SwapEffect:Int
	Field Flags:UInt
End Struct

Struct DXGI_SHARED_RESOURCE
	Field Handle:Byte Ptr
End Struct

Struct DXGI_GAMMA_CONTROL_CAPABILITIES
	Field ScaleAndOffsetSupported:Int
	Field MaxConvertedValue:Float
	Field MinConvertedValue:Float
	Field NumGammaControlPoints:UInt
	Field StaticArray ControlPointPositions:Float[1025]
End Struct

Struct DXGI_GAMMA_CONTROL
	Field Scale:DXGI_RGB
	Field Offset:DXGI_RGB
	Field StaticArray GammaCurve:DXGI_RGB[1025]
End Struct

Struct DXGI_SWAP_CHAIN_DESC1
	Field Width:UInt
	Field Height:UInt
	Field Format:Int
	Field Stereo:Int
	Field SampleDesc:DXGI_SAMPLE_DESC
	Field BufferUsage:UInt
	Field BufferCount:UInt
	Field Scaling:Int
	Field SwapEffect:Int
	Field AlphaMode:Int
	Field Flags:UInt
End Struct

Struct DXGI_SWAP_CHAIN_FULLSCREEN_DESC
	Field RefreshRate:DXGI_RATIONAL
	Field ScanlineOrdering:Int
	Field Scaling:Int
	Field Windowed:Int
End Struct

Struct DXGI_PRESENT_PARAMETERS
	Field DirtyRectsCount:UInt
	Field pDirtyRects:DXGI_RECT Ptr
	Field pScrollRect:DXGI_RECT Ptr
	Field pScrollOffset:DXGI_POINT Ptr
End Struct
