' Generated by tools/generate_bindings.py; complete vtable order from SDK headers.
SuperStrict

Import "common.bmx"

Extern "Win32"

Interface IDXGIObject Extends IUnknown_
	Method SetPrivateData:Int(p_guid:Byte Ptr, p_data_size:UInt, p_data:Byte Ptr)
	Method SetPrivateDataInterface:Int(p_guid:Byte Ptr, p_object:IUnknown_)
	Method GetPrivateData:Int(p_guid:Byte Ptr, p_data_size:UInt Ptr, p_data:Byte Ptr)
	Method GetParent:Int(p_riid:Byte Ptr, p_parent:Byte Ptr Ptr)
End Interface

Interface IDXGIDeviceSubObject Extends IDXGIObject
	Method GetDevice:Int(p_riid:Byte Ptr, p_device:Byte Ptr Ptr)
End Interface

Interface IDXGIResource Extends IDXGIDeviceSubObject
	Method GetSharedHandle:Int(p_pSharedHandle:Byte Ptr Ptr)
	Method GetUsage:Int(p_pUsage:UInt Ptr)
	Method SetEvictionPriority:Int(p_EvictionPriority:UInt)
	Method GetEvictionPriority:Int(p_pEvictionPriority:UInt Ptr)
End Interface

Interface IDXGISurface Extends IDXGIDeviceSubObject
	Method GetDesc:Int(p_desc:DXGI_SURFACE_DESC Ptr)
	Method Map:Int(p_mapped_rect:DXGI_MAPPED_RECT Ptr, p_flags:UInt)
	Method Unmap:Int()
End Interface

Interface IDXGISurface1 Extends IDXGISurface
	Method GetDC:Int(p_discard:Int, p_hdc:Byte Ptr Ptr)
	Method ReleaseDC:Int(p_dirty_rect:DXGI_RECT Ptr)
End Interface

Interface IDXGIOutput Extends IDXGIObject
	Method GetDesc:Int(p_desc:DXGI_OUTPUT_DESC Ptr)
	Method GetDisplayModeList:Int(p_format:Int, p_flags:UInt, p_mode_count:UInt Ptr, p_desc:DXGI_MODE_DESC Ptr)
	Method FindClosestMatchingMode:Int(p_mode:DXGI_MODE_DESC Ptr, p_closest_match:DXGI_MODE_DESC Ptr, p_device:IUnknown_)
	Method WaitForVBlank:Int()
	Method TakeOwnership:Int(p_device:IUnknown_, p_exclusive:Int)
	Method ReleaseOwnership()
	Method GetGammaControlCapabilities:Int(p_gamma_caps:DXGI_GAMMA_CONTROL_CAPABILITIES Ptr)
	Method SetGammaControl:Int(p_gamma_control:DXGI_GAMMA_CONTROL Ptr)
	Method GetGammaControl:Int(p_gamma_control:DXGI_GAMMA_CONTROL Ptr)
	Method SetDisplaySurface:Int(p_surface:IDXGISurface)
	Method GetDisplaySurfaceData:Int(p_surface:IDXGISurface)
	Method GetFrameStatistics:Int(p_stats:DXGI_FRAME_STATISTICS Ptr)
End Interface

Interface IDXGIAdapter Extends IDXGIObject
	Method EnumOutputs:Int(p_output_idx:UInt, p_output:IDXGIOutput Var)
	Method GetDesc:Int(p_desc:DXGI_ADAPTER_DESC Ptr)
	Method CheckInterfaceSupport:Int(p_guid:Byte Ptr, p_umd_version:Long Ptr)
End Interface

Interface IDXGISwapChain Extends IDXGIDeviceSubObject
	Method Present:Int(p_sync_interval:UInt, p_flags:UInt)
	Method GetBuffer:Int(p_buffer_idx:UInt, p_riid:Byte Ptr, p_surface:Byte Ptr Ptr)
	Method SetFullscreenState:Int(p_fullscreen:Int, p_target:IDXGIOutput)
	Method GetFullscreenState:Int(p_fullscreen:Int Ptr, p_target:IDXGIOutput Var)
	Method GetDesc:Int(p_desc:DXGI_SWAP_CHAIN_DESC Ptr)
	Method ResizeBuffers:Int(p_buffer_count:UInt, p_width:UInt, p_height:UInt, p_format:Int, p_flags:UInt)
	Method ResizeTarget:Int(p_target_mode_desc:DXGI_MODE_DESC Ptr)
	Method GetContainingOutput:Int(p_output:IDXGIOutput Var)
	Method GetFrameStatistics:Int(p_stats:DXGI_FRAME_STATISTICS Ptr)
	Method GetLastPresentCount:Int(p_last_present_count:UInt Ptr)
End Interface

Interface IDXGIFactory Extends IDXGIObject
	Method EnumAdapters:Int(p_adapter_idx:UInt, p_adapter:IDXGIAdapter Var)
	Method MakeWindowAssociation:Int(p_window:Byte Ptr, p_flags:UInt)
	Method GetWindowAssociation:Int(p_window:Byte Ptr Ptr)
	Method CreateSwapChain:Int(p_device:IUnknown_, p_desc:DXGI_SWAP_CHAIN_DESC Ptr, p_swapchain:IDXGISwapChain Var)
	Method CreateSoftwareAdapter:Int(p_swrast:Byte Ptr, p_adapter:IDXGIAdapter Var)
End Interface

Interface IDXGIDevice Extends IDXGIObject
	Method GetAdapter:Int(p_adapter:IDXGIAdapter Var)
	Method CreateSurface:Int(p_desc:DXGI_SURFACE_DESC Ptr, p_surface_count:UInt, p_usage:UInt, p_shared_resource:DXGI_SHARED_RESOURCE Ptr, p_surface:IDXGISurface Ptr)
	Method QueryResourceResidency:Int(p_resources:IUnknown_ Ptr, p_residency:Int Ptr, p_resource_count:UInt)
	Method SetGPUThreadPriority:Int(p_priority:Int)
	Method GetGPUThreadPriority:Int(p_priority:Int Ptr)
End Interface

Interface IDXGIAdapter1 Extends IDXGIAdapter
	Method GetDesc1:Int(p_pDesc:DXGI_ADAPTER_DESC1 Ptr)
End Interface

Interface IDXGIDevice1 Extends IDXGIDevice
	Method SetMaximumFrameLatency:Int(p_MaxLatency:UInt)
	Method GetMaximumFrameLatency:Int(p_pMaxLatency:UInt Ptr)
End Interface

Interface IDXGIFactory1 Extends IDXGIFactory
	Method EnumAdapters1:Int(p_Adapter:UInt, p_ppAdapter:IDXGIAdapter1 Var)
	Method IsCurrent:Int()
End Interface

Interface IDXGISwapChain1 Extends IDXGISwapChain
	Method GetDesc1:Int(p_pDesc:DXGI_SWAP_CHAIN_DESC1 Ptr)
	Method GetFullscreenDesc:Int(p_pDesc:DXGI_SWAP_CHAIN_FULLSCREEN_DESC Ptr)
	Method GetHwnd:Int(p_pHwnd:Byte Ptr Ptr)
	Method GetCoreWindow:Int(p_refiid:Byte Ptr, p_ppUnk:Byte Ptr Ptr)
	Method Present1:Int(p_SyncInterval:UInt, p_PresentFlags:UInt, p_pPresentParameters:DXGI_PRESENT_PARAMETERS Ptr)
	Method IsTemporaryMonoSupported:Int()
	Method GetRestrictToOutput:Int(p_ppRestrictToOutput:IDXGIOutput Var)
	Method SetBackgroundColor:Int(p_pColor:DXGI_RGBA Ptr)
	Method GetBackgroundColor:Int(p_pColor:DXGI_RGBA Ptr)
	Method SetRotation:Int(p_Rotation:Int)
	Method GetRotation:Int(p_pRotation:Int Ptr)
End Interface

Interface IDXGIFactory2 Extends IDXGIFactory1
	Method IsWindowedStereoEnabled:Int()
	Method CreateSwapChainForHwnd:Int(p_pDevice:IUnknown_, p_hWnd:Byte Ptr, p_pDesc:DXGI_SWAP_CHAIN_DESC1 Ptr, p_pFullscreenDesc:DXGI_SWAP_CHAIN_FULLSCREEN_DESC Ptr, p_pRestrictToOutput:IDXGIOutput, p_ppSwapChain:IDXGISwapChain1 Var)
	Method CreateSwapChainForCoreWindow:Int(p_pDevice:IUnknown_, p_pWindow:IUnknown_, p_pDesc:DXGI_SWAP_CHAIN_DESC1 Ptr, p_pRestrictToOutput:IDXGIOutput, p_ppSwapChain:IDXGISwapChain1 Var)
	Method GetSharedResourceAdapterLuid:Int(p_hResource:Byte Ptr, p_pLuid:DXGI_LUID Ptr)
	Method RegisterStereoStatusWindow:Int(p_WindowHandle:Byte Ptr, p_wMsg:UInt, p_pdwCookie:UInt Ptr)
	Method RegisterStereoStatusEvent:Int(p_hEvent:Byte Ptr, p_pdwCookie:UInt Ptr)
	Method UnregisterStereoStatus(p_dwCookie:UInt)
	Method RegisterOcclusionStatusWindow:Int(p_WindowHandle:Byte Ptr, p_wMsg:UInt, p_pdwCookie:UInt Ptr)
	Method RegisterOcclusionStatusEvent:Int(p_hEvent:Byte Ptr, p_pdwCookie:UInt Ptr)
	Method UnregisterOcclusionStatus(p_dwCookie:UInt)
	Method CreateSwapChainForComposition:Int(p_pDevice:IUnknown_, p_pDesc:DXGI_SWAP_CHAIN_DESC1 Ptr, p_pRestrictToOutput:IDXGIOutput, p_ppSwapChain:IDXGISwapChain1 Var)
End Interface

End Extern
