#include <d3d11.h>
#include <cstddef>
extern "C" int d3d11_test_layout(int type,int field){switch(type){
case 0:switch(field){case -1:return sizeof(D3D11_BUFFER_DESC);
case 0:return offsetof(D3D11_BUFFER_DESC,ByteWidth);
case 1:return offsetof(D3D11_BUFFER_DESC,Usage);
case 2:return offsetof(D3D11_BUFFER_DESC,BindFlags);
case 3:return offsetof(D3D11_BUFFER_DESC,CPUAccessFlags);
case 4:return offsetof(D3D11_BUFFER_DESC,MiscFlags);
case 5:return offsetof(D3D11_BUFFER_DESC,StructureByteStride);
}break;
case 1:switch(field){case -1:return sizeof(D3D11_TEXTURE1D_DESC);
case 0:return offsetof(D3D11_TEXTURE1D_DESC,Width);
case 1:return offsetof(D3D11_TEXTURE1D_DESC,MipLevels);
case 2:return offsetof(D3D11_TEXTURE1D_DESC,ArraySize);
case 3:return offsetof(D3D11_TEXTURE1D_DESC,Format);
case 4:return offsetof(D3D11_TEXTURE1D_DESC,Usage);
case 5:return offsetof(D3D11_TEXTURE1D_DESC,BindFlags);
case 6:return offsetof(D3D11_TEXTURE1D_DESC,CPUAccessFlags);
case 7:return offsetof(D3D11_TEXTURE1D_DESC,MiscFlags);
}break;
case 2:switch(field){case -1:return sizeof(D3D11_TEXTURE2D_DESC);
case 0:return offsetof(D3D11_TEXTURE2D_DESC,Width);
case 1:return offsetof(D3D11_TEXTURE2D_DESC,Height);
case 2:return offsetof(D3D11_TEXTURE2D_DESC,MipLevels);
case 3:return offsetof(D3D11_TEXTURE2D_DESC,ArraySize);
case 4:return offsetof(D3D11_TEXTURE2D_DESC,Format);
case 5:return offsetof(D3D11_TEXTURE2D_DESC,SampleDesc);
case 6:return offsetof(D3D11_TEXTURE2D_DESC,Usage);
case 7:return offsetof(D3D11_TEXTURE2D_DESC,BindFlags);
case 8:return offsetof(D3D11_TEXTURE2D_DESC,CPUAccessFlags);
case 9:return offsetof(D3D11_TEXTURE2D_DESC,MiscFlags);
}break;
case 3:switch(field){case -1:return sizeof(D3D11_TEXTURE3D_DESC);
case 0:return offsetof(D3D11_TEXTURE3D_DESC,Width);
case 1:return offsetof(D3D11_TEXTURE3D_DESC,Height);
case 2:return offsetof(D3D11_TEXTURE3D_DESC,Depth);
case 3:return offsetof(D3D11_TEXTURE3D_DESC,MipLevels);
case 4:return offsetof(D3D11_TEXTURE3D_DESC,Format);
case 5:return offsetof(D3D11_TEXTURE3D_DESC,Usage);
case 6:return offsetof(D3D11_TEXTURE3D_DESC,BindFlags);
case 7:return offsetof(D3D11_TEXTURE3D_DESC,CPUAccessFlags);
case 8:return offsetof(D3D11_TEXTURE3D_DESC,MiscFlags);
}break;
case 4:switch(field){case -1:return sizeof(D3D11_SUBRESOURCE_DATA);
case 0:return offsetof(D3D11_SUBRESOURCE_DATA,pSysMem);
case 1:return offsetof(D3D11_SUBRESOURCE_DATA,SysMemPitch);
case 2:return offsetof(D3D11_SUBRESOURCE_DATA,SysMemSlicePitch);
}break;
case 5:switch(field){case -1:return sizeof(D3D11_MAPPED_SUBRESOURCE);
case 0:return offsetof(D3D11_MAPPED_SUBRESOURCE,pData);
case 1:return offsetof(D3D11_MAPPED_SUBRESOURCE,RowPitch);
case 2:return offsetof(D3D11_MAPPED_SUBRESOURCE,DepthPitch);
}break;
case 6:switch(field){case -1:return sizeof(D3D11_BOX);
case 0:return offsetof(D3D11_BOX,left);
case 1:return offsetof(D3D11_BOX,top);
case 2:return offsetof(D3D11_BOX,front);
case 3:return offsetof(D3D11_BOX,right);
case 4:return offsetof(D3D11_BOX,bottom);
case 5:return offsetof(D3D11_BOX,back);
}break;
case 7:switch(field){case -1:return sizeof(D3D11_VIEWPORT);
case 0:return offsetof(D3D11_VIEWPORT,TopLeftX);
case 1:return offsetof(D3D11_VIEWPORT,TopLeftY);
case 2:return offsetof(D3D11_VIEWPORT,Width);
case 3:return offsetof(D3D11_VIEWPORT,Height);
case 4:return offsetof(D3D11_VIEWPORT,MinDepth);
case 5:return offsetof(D3D11_VIEWPORT,MaxDepth);
}break;
case 8:switch(field){case -1:return sizeof(D3D11_INPUT_ELEMENT_DESC);
case 0:return offsetof(D3D11_INPUT_ELEMENT_DESC,SemanticName);
case 1:return offsetof(D3D11_INPUT_ELEMENT_DESC,SemanticIndex);
case 2:return offsetof(D3D11_INPUT_ELEMENT_DESC,Format);
case 3:return offsetof(D3D11_INPUT_ELEMENT_DESC,InputSlot);
case 4:return offsetof(D3D11_INPUT_ELEMENT_DESC,AlignedByteOffset);
case 5:return offsetof(D3D11_INPUT_ELEMENT_DESC,InputSlotClass);
case 6:return offsetof(D3D11_INPUT_ELEMENT_DESC,InstanceDataStepRate);
}break;
case 9:switch(field){case -1:return sizeof(D3D11_SAMPLER_DESC);
case 0:return offsetof(D3D11_SAMPLER_DESC,Filter);
case 1:return offsetof(D3D11_SAMPLER_DESC,AddressU);
case 2:return offsetof(D3D11_SAMPLER_DESC,AddressV);
case 3:return offsetof(D3D11_SAMPLER_DESC,AddressW);
case 4:return offsetof(D3D11_SAMPLER_DESC,MipLODBias);
case 5:return offsetof(D3D11_SAMPLER_DESC,MaxAnisotropy);
case 6:return offsetof(D3D11_SAMPLER_DESC,ComparisonFunc);
case 7:return offsetof(D3D11_SAMPLER_DESC,BorderColor);
case 8:return offsetof(D3D11_SAMPLER_DESC,MinLOD);
case 9:return offsetof(D3D11_SAMPLER_DESC,MaxLOD);
}break;
case 10:switch(field){case -1:return sizeof(D3D11_RENDER_TARGET_BLEND_DESC);
case 0:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,BlendEnable);
case 1:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,SrcBlend);
case 2:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,DestBlend);
case 3:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,BlendOp);
case 4:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,SrcBlendAlpha);
case 5:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,DestBlendAlpha);
case 6:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,BlendOpAlpha);
case 7:return offsetof(D3D11_RENDER_TARGET_BLEND_DESC,RenderTargetWriteMask);
}break;
case 11:switch(field){case -1:return sizeof(D3D11_BLEND_DESC);
case 0:return offsetof(D3D11_BLEND_DESC,AlphaToCoverageEnable);
case 1:return offsetof(D3D11_BLEND_DESC,IndependentBlendEnable);
case 2:return offsetof(D3D11_BLEND_DESC,RenderTarget);
}break;
case 12:switch(field){case -1:return sizeof(D3D11_DEPTH_STENCILOP_DESC);
case 0:return offsetof(D3D11_DEPTH_STENCILOP_DESC,StencilFailOp);
case 1:return offsetof(D3D11_DEPTH_STENCILOP_DESC,StencilDepthFailOp);
case 2:return offsetof(D3D11_DEPTH_STENCILOP_DESC,StencilPassOp);
case 3:return offsetof(D3D11_DEPTH_STENCILOP_DESC,StencilFunc);
}break;
case 13:switch(field){case -1:return sizeof(D3D11_DEPTH_STENCIL_DESC);
case 0:return offsetof(D3D11_DEPTH_STENCIL_DESC,DepthEnable);
case 1:return offsetof(D3D11_DEPTH_STENCIL_DESC,DepthWriteMask);
case 2:return offsetof(D3D11_DEPTH_STENCIL_DESC,DepthFunc);
case 3:return offsetof(D3D11_DEPTH_STENCIL_DESC,StencilEnable);
case 4:return offsetof(D3D11_DEPTH_STENCIL_DESC,StencilReadMask);
case 5:return offsetof(D3D11_DEPTH_STENCIL_DESC,StencilWriteMask);
case 6:return offsetof(D3D11_DEPTH_STENCIL_DESC,FrontFace);
case 7:return offsetof(D3D11_DEPTH_STENCIL_DESC,BackFace);
}break;
case 14:switch(field){case -1:return sizeof(D3D11_RASTERIZER_DESC);
case 0:return offsetof(D3D11_RASTERIZER_DESC,FillMode);
case 1:return offsetof(D3D11_RASTERIZER_DESC,CullMode);
case 2:return offsetof(D3D11_RASTERIZER_DESC,FrontCounterClockwise);
case 3:return offsetof(D3D11_RASTERIZER_DESC,DepthBias);
case 4:return offsetof(D3D11_RASTERIZER_DESC,DepthBiasClamp);
case 5:return offsetof(D3D11_RASTERIZER_DESC,SlopeScaledDepthBias);
case 6:return offsetof(D3D11_RASTERIZER_DESC,DepthClipEnable);
case 7:return offsetof(D3D11_RASTERIZER_DESC,ScissorEnable);
case 8:return offsetof(D3D11_RASTERIZER_DESC,MultisampleEnable);
case 9:return offsetof(D3D11_RASTERIZER_DESC,AntialiasedLineEnable);
}break;
case 15:switch(field){case -1:return sizeof(D3D11_QUERY_DESC);
case 0:return offsetof(D3D11_QUERY_DESC,Query);
case 1:return offsetof(D3D11_QUERY_DESC,MiscFlags);
}break;
case 16:switch(field){case -1:return sizeof(D3D11_COUNTER_DESC);
case 0:return offsetof(D3D11_COUNTER_DESC,Counter);
case 1:return offsetof(D3D11_COUNTER_DESC,MiscFlags);
}break;
case 17:switch(field){case -1:return sizeof(D3D11_CLASS_INSTANCE_DESC);
case 0:return offsetof(D3D11_CLASS_INSTANCE_DESC,InstanceId);
case 1:return offsetof(D3D11_CLASS_INSTANCE_DESC,InstanceIndex);
case 2:return offsetof(D3D11_CLASS_INSTANCE_DESC,TypeId);
case 3:return offsetof(D3D11_CLASS_INSTANCE_DESC,ConstantBuffer);
case 4:return offsetof(D3D11_CLASS_INSTANCE_DESC,BaseConstantBufferOffset);
case 5:return offsetof(D3D11_CLASS_INSTANCE_DESC,BaseTexture);
case 6:return offsetof(D3D11_CLASS_INSTANCE_DESC,BaseSampler);
case 7:return offsetof(D3D11_CLASS_INSTANCE_DESC,Created);
}break;
}return -1;}
