SuperStrict
Framework BRL.StandardIO
Import Pub.Direct3D11
Import "layouts.cpp"
Extern "C"
 Function d3d11_test_layout:Int(kind:Int,field:Int)
End Extern
Function Check(ok:Int,label:String)
 If Not ok Then Throw label
End Function
Try
 Local v0:D3D11_BUFFER_DESC
 Check(SizeOf(v0)=d3d11_test_layout(0,-1),"sizeof D3D11_BUFFER_DESC")
 Check(Byte Ptr(Varptr v0.ByteWidth)-Byte Ptr(Varptr v0)=d3d11_test_layout(0,0),"offset D3D11_BUFFER_DESC.ByteWidth")
 Check(Byte Ptr(Varptr v0.Usage)-Byte Ptr(Varptr v0)=d3d11_test_layout(0,1),"offset D3D11_BUFFER_DESC.Usage")
 Check(Byte Ptr(Varptr v0.BindFlags)-Byte Ptr(Varptr v0)=d3d11_test_layout(0,2),"offset D3D11_BUFFER_DESC.BindFlags")
 Check(Byte Ptr(Varptr v0.CPUAccessFlags)-Byte Ptr(Varptr v0)=d3d11_test_layout(0,3),"offset D3D11_BUFFER_DESC.CPUAccessFlags")
 Check(Byte Ptr(Varptr v0.MiscFlags)-Byte Ptr(Varptr v0)=d3d11_test_layout(0,4),"offset D3D11_BUFFER_DESC.MiscFlags")
 Check(Byte Ptr(Varptr v0.StructureByteStride)-Byte Ptr(Varptr v0)=d3d11_test_layout(0,5),"offset D3D11_BUFFER_DESC.StructureByteStride")
 Local v1:D3D11_TEXTURE1D_DESC
 Check(SizeOf(v1)=d3d11_test_layout(1,-1),"sizeof D3D11_TEXTURE1D_DESC")
 Check(Byte Ptr(Varptr v1.Width)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,0),"offset D3D11_TEXTURE1D_DESC.Width")
 Check(Byte Ptr(Varptr v1.MipLevels)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,1),"offset D3D11_TEXTURE1D_DESC.MipLevels")
 Check(Byte Ptr(Varptr v1.ArraySize)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,2),"offset D3D11_TEXTURE1D_DESC.ArraySize")
 Check(Byte Ptr(Varptr v1.Format)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,3),"offset D3D11_TEXTURE1D_DESC.Format")
 Check(Byte Ptr(Varptr v1.Usage)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,4),"offset D3D11_TEXTURE1D_DESC.Usage")
 Check(Byte Ptr(Varptr v1.BindFlags)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,5),"offset D3D11_TEXTURE1D_DESC.BindFlags")
 Check(Byte Ptr(Varptr v1.CPUAccessFlags)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,6),"offset D3D11_TEXTURE1D_DESC.CPUAccessFlags")
 Check(Byte Ptr(Varptr v1.MiscFlags)-Byte Ptr(Varptr v1)=d3d11_test_layout(1,7),"offset D3D11_TEXTURE1D_DESC.MiscFlags")
 Local v2:D3D11_TEXTURE2D_DESC
 Check(SizeOf(v2)=d3d11_test_layout(2,-1),"sizeof D3D11_TEXTURE2D_DESC")
 Check(Byte Ptr(Varptr v2.Width)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,0),"offset D3D11_TEXTURE2D_DESC.Width")
 Check(Byte Ptr(Varptr v2.Height)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,1),"offset D3D11_TEXTURE2D_DESC.Height")
 Check(Byte Ptr(Varptr v2.MipLevels)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,2),"offset D3D11_TEXTURE2D_DESC.MipLevels")
 Check(Byte Ptr(Varptr v2.ArraySize)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,3),"offset D3D11_TEXTURE2D_DESC.ArraySize")
 Check(Byte Ptr(Varptr v2.Format)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,4),"offset D3D11_TEXTURE2D_DESC.Format")
 Check(Byte Ptr(Varptr v2.SampleDesc)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,5),"offset D3D11_TEXTURE2D_DESC.SampleDesc")
 Check(Byte Ptr(Varptr v2.Usage)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,6),"offset D3D11_TEXTURE2D_DESC.Usage")
 Check(Byte Ptr(Varptr v2.BindFlags)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,7),"offset D3D11_TEXTURE2D_DESC.BindFlags")
 Check(Byte Ptr(Varptr v2.CPUAccessFlags)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,8),"offset D3D11_TEXTURE2D_DESC.CPUAccessFlags")
 Check(Byte Ptr(Varptr v2.MiscFlags)-Byte Ptr(Varptr v2)=d3d11_test_layout(2,9),"offset D3D11_TEXTURE2D_DESC.MiscFlags")
 Local v3:D3D11_TEXTURE3D_DESC
 Check(SizeOf(v3)=d3d11_test_layout(3,-1),"sizeof D3D11_TEXTURE3D_DESC")
 Check(Byte Ptr(Varptr v3.Width)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,0),"offset D3D11_TEXTURE3D_DESC.Width")
 Check(Byte Ptr(Varptr v3.Height)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,1),"offset D3D11_TEXTURE3D_DESC.Height")
 Check(Byte Ptr(Varptr v3.Depth)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,2),"offset D3D11_TEXTURE3D_DESC.Depth")
 Check(Byte Ptr(Varptr v3.MipLevels)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,3),"offset D3D11_TEXTURE3D_DESC.MipLevels")
 Check(Byte Ptr(Varptr v3.Format)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,4),"offset D3D11_TEXTURE3D_DESC.Format")
 Check(Byte Ptr(Varptr v3.Usage)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,5),"offset D3D11_TEXTURE3D_DESC.Usage")
 Check(Byte Ptr(Varptr v3.BindFlags)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,6),"offset D3D11_TEXTURE3D_DESC.BindFlags")
 Check(Byte Ptr(Varptr v3.CPUAccessFlags)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,7),"offset D3D11_TEXTURE3D_DESC.CPUAccessFlags")
 Check(Byte Ptr(Varptr v3.MiscFlags)-Byte Ptr(Varptr v3)=d3d11_test_layout(3,8),"offset D3D11_TEXTURE3D_DESC.MiscFlags")
 Local v4:D3D11_SUBRESOURCE_DATA
 Check(SizeOf(v4)=d3d11_test_layout(4,-1),"sizeof D3D11_SUBRESOURCE_DATA")
 Check(Byte Ptr(Varptr v4.pSysMem)-Byte Ptr(Varptr v4)=d3d11_test_layout(4,0),"offset D3D11_SUBRESOURCE_DATA.pSysMem")
 Check(Byte Ptr(Varptr v4.SysMemPitch)-Byte Ptr(Varptr v4)=d3d11_test_layout(4,1),"offset D3D11_SUBRESOURCE_DATA.SysMemPitch")
 Check(Byte Ptr(Varptr v4.SysMemSlicePitch)-Byte Ptr(Varptr v4)=d3d11_test_layout(4,2),"offset D3D11_SUBRESOURCE_DATA.SysMemSlicePitch")
 Local v5:D3D11_MAPPED_SUBRESOURCE
 Check(SizeOf(v5)=d3d11_test_layout(5,-1),"sizeof D3D11_MAPPED_SUBRESOURCE")
 Check(Byte Ptr(Varptr v5.pData)-Byte Ptr(Varptr v5)=d3d11_test_layout(5,0),"offset D3D11_MAPPED_SUBRESOURCE.pData")
 Check(Byte Ptr(Varptr v5.RowPitch)-Byte Ptr(Varptr v5)=d3d11_test_layout(5,1),"offset D3D11_MAPPED_SUBRESOURCE.RowPitch")
 Check(Byte Ptr(Varptr v5.DepthPitch)-Byte Ptr(Varptr v5)=d3d11_test_layout(5,2),"offset D3D11_MAPPED_SUBRESOURCE.DepthPitch")
 Local v6:D3D11_BOX
 Check(SizeOf(v6)=d3d11_test_layout(6,-1),"sizeof D3D11_BOX")
 Check(Byte Ptr(Varptr v6.left)-Byte Ptr(Varptr v6)=d3d11_test_layout(6,0),"offset D3D11_BOX.left")
 Check(Byte Ptr(Varptr v6.top)-Byte Ptr(Varptr v6)=d3d11_test_layout(6,1),"offset D3D11_BOX.top")
 Check(Byte Ptr(Varptr v6.front)-Byte Ptr(Varptr v6)=d3d11_test_layout(6,2),"offset D3D11_BOX.front")
 Check(Byte Ptr(Varptr v6.right)-Byte Ptr(Varptr v6)=d3d11_test_layout(6,3),"offset D3D11_BOX.right")
 Check(Byte Ptr(Varptr v6.bottom)-Byte Ptr(Varptr v6)=d3d11_test_layout(6,4),"offset D3D11_BOX.bottom")
 Check(Byte Ptr(Varptr v6.back)-Byte Ptr(Varptr v6)=d3d11_test_layout(6,5),"offset D3D11_BOX.back")
 Local v7:D3D11_VIEWPORT
 Check(SizeOf(v7)=d3d11_test_layout(7,-1),"sizeof D3D11_VIEWPORT")
 Check(Byte Ptr(Varptr v7.TopLeftX)-Byte Ptr(Varptr v7)=d3d11_test_layout(7,0),"offset D3D11_VIEWPORT.TopLeftX")
 Check(Byte Ptr(Varptr v7.TopLeftY)-Byte Ptr(Varptr v7)=d3d11_test_layout(7,1),"offset D3D11_VIEWPORT.TopLeftY")
 Check(Byte Ptr(Varptr v7.Width)-Byte Ptr(Varptr v7)=d3d11_test_layout(7,2),"offset D3D11_VIEWPORT.Width")
 Check(Byte Ptr(Varptr v7.Height)-Byte Ptr(Varptr v7)=d3d11_test_layout(7,3),"offset D3D11_VIEWPORT.Height")
 Check(Byte Ptr(Varptr v7.MinDepth)-Byte Ptr(Varptr v7)=d3d11_test_layout(7,4),"offset D3D11_VIEWPORT.MinDepth")
 Check(Byte Ptr(Varptr v7.MaxDepth)-Byte Ptr(Varptr v7)=d3d11_test_layout(7,5),"offset D3D11_VIEWPORT.MaxDepth")
 Local v8:D3D11_INPUT_ELEMENT_DESC
 Check(SizeOf(v8)=d3d11_test_layout(8,-1),"sizeof D3D11_INPUT_ELEMENT_DESC")
 Check(Byte Ptr(Varptr v8.SemanticName)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,0),"offset D3D11_INPUT_ELEMENT_DESC.SemanticName")
 Check(Byte Ptr(Varptr v8.SemanticIndex)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,1),"offset D3D11_INPUT_ELEMENT_DESC.SemanticIndex")
 Check(Byte Ptr(Varptr v8.Format)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,2),"offset D3D11_INPUT_ELEMENT_DESC.Format")
 Check(Byte Ptr(Varptr v8.InputSlot)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,3),"offset D3D11_INPUT_ELEMENT_DESC.InputSlot")
 Check(Byte Ptr(Varptr v8.AlignedByteOffset)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,4),"offset D3D11_INPUT_ELEMENT_DESC.AlignedByteOffset")
 Check(Byte Ptr(Varptr v8.InputSlotClass)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,5),"offset D3D11_INPUT_ELEMENT_DESC.InputSlotClass")
 Check(Byte Ptr(Varptr v8.InstanceDataStepRate)-Byte Ptr(Varptr v8)=d3d11_test_layout(8,6),"offset D3D11_INPUT_ELEMENT_DESC.InstanceDataStepRate")
 Local v9:D3D11_SAMPLER_DESC
 Check(SizeOf(v9)=d3d11_test_layout(9,-1),"sizeof D3D11_SAMPLER_DESC")
 Check(Byte Ptr(Varptr v9.Filter)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,0),"offset D3D11_SAMPLER_DESC.Filter")
 Check(Byte Ptr(Varptr v9.AddressU)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,1),"offset D3D11_SAMPLER_DESC.AddressU")
 Check(Byte Ptr(Varptr v9.AddressV)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,2),"offset D3D11_SAMPLER_DESC.AddressV")
 Check(Byte Ptr(Varptr v9.AddressW)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,3),"offset D3D11_SAMPLER_DESC.AddressW")
 Check(Byte Ptr(Varptr v9.MipLODBias)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,4),"offset D3D11_SAMPLER_DESC.MipLODBias")
 Check(Byte Ptr(Varptr v9.MaxAnisotropy)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,5),"offset D3D11_SAMPLER_DESC.MaxAnisotropy")
 Check(Byte Ptr(Varptr v9.ComparisonFunc)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,6),"offset D3D11_SAMPLER_DESC.ComparisonFunc")
 Check(Byte Ptr(Varptr v9.BorderColor[0])-Byte Ptr(Varptr v9)=d3d11_test_layout(9,7),"offset D3D11_SAMPLER_DESC.BorderColor")
 Check(Byte Ptr(Varptr v9.MinLOD)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,8),"offset D3D11_SAMPLER_DESC.MinLOD")
 Check(Byte Ptr(Varptr v9.MaxLOD)-Byte Ptr(Varptr v9)=d3d11_test_layout(9,9),"offset D3D11_SAMPLER_DESC.MaxLOD")
 Local v10:D3D11_RENDER_TARGET_BLEND_DESC
 Check(SizeOf(v10)=d3d11_test_layout(10,-1),"sizeof D3D11_RENDER_TARGET_BLEND_DESC")
 Check(Byte Ptr(Varptr v10.BlendEnable)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,0),"offset D3D11_RENDER_TARGET_BLEND_DESC.BlendEnable")
 Check(Byte Ptr(Varptr v10.SrcBlend)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,1),"offset D3D11_RENDER_TARGET_BLEND_DESC.SrcBlend")
 Check(Byte Ptr(Varptr v10.DestBlend)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,2),"offset D3D11_RENDER_TARGET_BLEND_DESC.DestBlend")
 Check(Byte Ptr(Varptr v10.BlendOp)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,3),"offset D3D11_RENDER_TARGET_BLEND_DESC.BlendOp")
 Check(Byte Ptr(Varptr v10.SrcBlendAlpha)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,4),"offset D3D11_RENDER_TARGET_BLEND_DESC.SrcBlendAlpha")
 Check(Byte Ptr(Varptr v10.DestBlendAlpha)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,5),"offset D3D11_RENDER_TARGET_BLEND_DESC.DestBlendAlpha")
 Check(Byte Ptr(Varptr v10.BlendOpAlpha)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,6),"offset D3D11_RENDER_TARGET_BLEND_DESC.BlendOpAlpha")
 Check(Byte Ptr(Varptr v10.RenderTargetWriteMask)-Byte Ptr(Varptr v10)=d3d11_test_layout(10,7),"offset D3D11_RENDER_TARGET_BLEND_DESC.RenderTargetWriteMask")
 Local v11:D3D11_BLEND_DESC
 Check(SizeOf(v11)=d3d11_test_layout(11,-1),"sizeof D3D11_BLEND_DESC")
 Check(Byte Ptr(Varptr v11.AlphaToCoverageEnable)-Byte Ptr(Varptr v11)=d3d11_test_layout(11,0),"offset D3D11_BLEND_DESC.AlphaToCoverageEnable")
 Check(Byte Ptr(Varptr v11.IndependentBlendEnable)-Byte Ptr(Varptr v11)=d3d11_test_layout(11,1),"offset D3D11_BLEND_DESC.IndependentBlendEnable")
 Check(Byte Ptr(Varptr v11.RenderTarget[0])-Byte Ptr(Varptr v11)=d3d11_test_layout(11,2),"offset D3D11_BLEND_DESC.RenderTarget")
 Local v12:D3D11_DEPTH_STENCILOP_DESC
 Check(SizeOf(v12)=d3d11_test_layout(12,-1),"sizeof D3D11_DEPTH_STENCILOP_DESC")
 Check(Byte Ptr(Varptr v12.StencilFailOp)-Byte Ptr(Varptr v12)=d3d11_test_layout(12,0),"offset D3D11_DEPTH_STENCILOP_DESC.StencilFailOp")
 Check(Byte Ptr(Varptr v12.StencilDepthFailOp)-Byte Ptr(Varptr v12)=d3d11_test_layout(12,1),"offset D3D11_DEPTH_STENCILOP_DESC.StencilDepthFailOp")
 Check(Byte Ptr(Varptr v12.StencilPassOp)-Byte Ptr(Varptr v12)=d3d11_test_layout(12,2),"offset D3D11_DEPTH_STENCILOP_DESC.StencilPassOp")
 Check(Byte Ptr(Varptr v12.StencilFunc)-Byte Ptr(Varptr v12)=d3d11_test_layout(12,3),"offset D3D11_DEPTH_STENCILOP_DESC.StencilFunc")
 Local v13:D3D11_DEPTH_STENCIL_DESC
 Check(SizeOf(v13)=d3d11_test_layout(13,-1),"sizeof D3D11_DEPTH_STENCIL_DESC")
 Check(Byte Ptr(Varptr v13.DepthEnable)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,0),"offset D3D11_DEPTH_STENCIL_DESC.DepthEnable")
 Check(Byte Ptr(Varptr v13.DepthWriteMask)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,1),"offset D3D11_DEPTH_STENCIL_DESC.DepthWriteMask")
 Check(Byte Ptr(Varptr v13.DepthFunc)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,2),"offset D3D11_DEPTH_STENCIL_DESC.DepthFunc")
 Check(Byte Ptr(Varptr v13.StencilEnable)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,3),"offset D3D11_DEPTH_STENCIL_DESC.StencilEnable")
 Check(Byte Ptr(Varptr v13.StencilReadMask)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,4),"offset D3D11_DEPTH_STENCIL_DESC.StencilReadMask")
 Check(Byte Ptr(Varptr v13.StencilWriteMask)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,5),"offset D3D11_DEPTH_STENCIL_DESC.StencilWriteMask")
 Check(Byte Ptr(Varptr v13.FrontFace)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,6),"offset D3D11_DEPTH_STENCIL_DESC.FrontFace")
 Check(Byte Ptr(Varptr v13.BackFace)-Byte Ptr(Varptr v13)=d3d11_test_layout(13,7),"offset D3D11_DEPTH_STENCIL_DESC.BackFace")
 Local v14:D3D11_RASTERIZER_DESC
 Check(SizeOf(v14)=d3d11_test_layout(14,-1),"sizeof D3D11_RASTERIZER_DESC")
 Check(Byte Ptr(Varptr v14.FillMode)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,0),"offset D3D11_RASTERIZER_DESC.FillMode")
 Check(Byte Ptr(Varptr v14.CullMode)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,1),"offset D3D11_RASTERIZER_DESC.CullMode")
 Check(Byte Ptr(Varptr v14.FrontCounterClockwise)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,2),"offset D3D11_RASTERIZER_DESC.FrontCounterClockwise")
 Check(Byte Ptr(Varptr v14.DepthBias)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,3),"offset D3D11_RASTERIZER_DESC.DepthBias")
 Check(Byte Ptr(Varptr v14.DepthBiasClamp)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,4),"offset D3D11_RASTERIZER_DESC.DepthBiasClamp")
 Check(Byte Ptr(Varptr v14.SlopeScaledDepthBias)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,5),"offset D3D11_RASTERIZER_DESC.SlopeScaledDepthBias")
 Check(Byte Ptr(Varptr v14.DepthClipEnable)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,6),"offset D3D11_RASTERIZER_DESC.DepthClipEnable")
 Check(Byte Ptr(Varptr v14.ScissorEnable)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,7),"offset D3D11_RASTERIZER_DESC.ScissorEnable")
 Check(Byte Ptr(Varptr v14.MultisampleEnable)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,8),"offset D3D11_RASTERIZER_DESC.MultisampleEnable")
 Check(Byte Ptr(Varptr v14.AntialiasedLineEnable)-Byte Ptr(Varptr v14)=d3d11_test_layout(14,9),"offset D3D11_RASTERIZER_DESC.AntialiasedLineEnable")
 Local v15:D3D11_QUERY_DESC
 Check(SizeOf(v15)=d3d11_test_layout(15,-1),"sizeof D3D11_QUERY_DESC")
 Check(Byte Ptr(Varptr v15.Query)-Byte Ptr(Varptr v15)=d3d11_test_layout(15,0),"offset D3D11_QUERY_DESC.Query")
 Check(Byte Ptr(Varptr v15.MiscFlags)-Byte Ptr(Varptr v15)=d3d11_test_layout(15,1),"offset D3D11_QUERY_DESC.MiscFlags")
 Local v16:D3D11_COUNTER_DESC
 Check(SizeOf(v16)=d3d11_test_layout(16,-1),"sizeof D3D11_COUNTER_DESC")
 Check(Byte Ptr(Varptr v16.Counter)-Byte Ptr(Varptr v16)=d3d11_test_layout(16,0),"offset D3D11_COUNTER_DESC.Counter")
 Check(Byte Ptr(Varptr v16.MiscFlags)-Byte Ptr(Varptr v16)=d3d11_test_layout(16,1),"offset D3D11_COUNTER_DESC.MiscFlags")
 Local v17:D3D11_CLASS_INSTANCE_DESC
 Check(SizeOf(v17)=d3d11_test_layout(17,-1),"sizeof D3D11_CLASS_INSTANCE_DESC")
 Check(Byte Ptr(Varptr v17.InstanceId)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,0),"offset D3D11_CLASS_INSTANCE_DESC.InstanceId")
 Check(Byte Ptr(Varptr v17.InstanceIndex)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,1),"offset D3D11_CLASS_INSTANCE_DESC.InstanceIndex")
 Check(Byte Ptr(Varptr v17.TypeId)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,2),"offset D3D11_CLASS_INSTANCE_DESC.TypeId")
 Check(Byte Ptr(Varptr v17.ConstantBuffer)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,3),"offset D3D11_CLASS_INSTANCE_DESC.ConstantBuffer")
 Check(Byte Ptr(Varptr v17.BaseConstantBufferOffset)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,4),"offset D3D11_CLASS_INSTANCE_DESC.BaseConstantBufferOffset")
 Check(Byte Ptr(Varptr v17.BaseTexture)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,5),"offset D3D11_CLASS_INSTANCE_DESC.BaseTexture")
 Check(Byte Ptr(Varptr v17.BaseSampler)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,6),"offset D3D11_CLASS_INSTANCE_DESC.BaseSampler")
 Check(Byte Ptr(Varptr v17.Created)-Byte Ptr(Varptr v17)=d3d11_test_layout(17,7),"offset D3D11_CLASS_INSTANCE_DESC.Created")
 Print "Pub.Direct3D11: 131 layout checks passed"
Catch e:Object
 Print "FAILED: "+e.ToString()
 EndWithCode(1)
End Try
