
SuperStrict

Import "include/*.h"
Import "d3d.cpp"

Const D3DADAPTER_DEFAULT:Int=0

Const D3DENUMRET_CANCEL:Int=0
Const D3DENUMRET_OK:Int=1

Const D3DSTATUS:Int=$08760000
Const D3DHRESULT:Int=$88760000

Const D3DERR_WRONGTEXTUREFORMAT:Int=D3DHRESULT|2072
Const D3DERR_UNSUPPORTEDCOLOROPERATION:Int=D3DHRESULT|2073
Const D3DERR_UNSUPPORTEDCOLORARG:Int=D3DHRESULT|2074
Const D3DERR_UNSUPPORTEDALPHAOPERATION:Int=D3DHRESULT|2075
Const D3DERR_UNSUPPORTEDALPHAARG:Int=D3DHRESULT|2076
Const D3DERR_TOOMANYOPERATIONS:Int=D3DHRESULT|2077
Const D3DERR_CONFLICTINGTEXTUREFILTER:Int=D3DHRESULT|2078
Const D3DERR_UNSUPPORTEDFACTORVALUE:Int=D3DHRESULT|2079
Const D3DERR_CONFLICTINGRENDERSTATE:Int=D3DHRESULT|2081
Const D3DERR_UNSUPPORTEDTEXTUREFILTER:Int=D3DHRESULT|2082
Const D3DERR_CONFLICTINGTEXTUREPALETTE:Int=D3DHRESULT|2086
Const D3DERR_DRIVERINTERNALERROR:Int=D3DHRESULT|2087
Const D3DERR_NOTFOUND:Int=D3DHRESULT|2150
Const D3DERR_MOREDATA:Int=D3DHRESULT|2151
Const D3DERR_DEVICELOST:Int=D3DHRESULT|2152
Const D3DERR_DEVICENOTRESET:Int=D3DHRESULT|2153
Const D3DERR_NOTAVAILABLE:Int=D3DHRESULT|2154
Const D3DERR_OUTOFVIDEOMEMORY:Int=D3DHRESULT|380
Const D3DERR_INVALIDDEVICE:Int=D3DHRESULT|2155
Const D3DERR_INVALIDCALL:Int=D3DHRESULT|2156
Const D3DERR_DRIVERINVALIDCALL:Int=D3DHRESULT|2157
Const D3DERR_WASSTILLDRAWING:Int=D3DHRESULT|540

Const D3D_OK:Int=0
Const D3DOK_NOAUTOGEN:Int=D3DSTATUS|2159

Const D3DLOCK_READONLY:Int=$10
Const D3DLOCK_DISCARD:Int=$2000
Const D3DLOCK_NOOVERWRITE:Int=$1000
Const D3DLOCK_NOSYSLOCK:Int=$800
Const D3DLOCK_DONOTWAIT:Int=$4000
Const D3DLOCK_NO_DIRTY_UPDATE:Int=$8000

Const D3DUSAGE_RENDERTARGET:Int=$1
Const D3DUSAGE_DEPTHSTENCIL:Int=$2
Const D3DUSAGE_DYNAMIC:Int=$200
Const D3DUSAGE_AUTOGENMIPMAP:Int=$400
Const D3DUSAGE_DMAP:Int=$4000
Const D3DUSAGE_QUERY_LEGACYBUMPMAP:Int=$8000
Const D3DUSAGE_QUERY_SRGBREAD:Int=$10000
Const D3DUSAGE_QUERY_FILTER:Int=$20000
Const D3DUSAGE_QUERY_SRGBWRITE:Int=$40000
Const D3DUSAGE_QUERY_POSTPIXELSHADER_BLENDING:Int=$80000
Const D3DUSAGE_QUERY_VERTEXTEXTURE:Int=$100000
Const D3DUSAGE_WRITEONLY:Int=$8
Const D3DUSAGE_SOFTWAREPROCESSING:Int=$10
Const D3DUSAGE_DONOTCLIP:Int=$20
Const D3DUSAGE_POINTS:Int=$40
Const D3DUSAGE_RTPATCHES:Int=$80
Const D3DUSAGE_NPATCHES:Int=$100

'D3DTEXTUREADDRESS
Const D3DTADDRESS_WRAP:Int=1
Const D3DTADDRESS_MIRROR:Int=2
Const D3DTADDRESS_CLAMP:Int=3
Const D3DTADDRESS_BORDER:Int=4
Const D3DTADDRESS_MIRRORONCE:Int=5

'D3DMATERIALCOLORSOURCE
Const D3DMCS_MATERIAL:Int=0
Const D3DMCS_COLOR1:Int=1
Const D3DMCS_COLOR2:Int=2

'D3DBLEND
Const D3DBLEND_ZERO:Int=1
Const D3DBLEND_ONE:Int=2
Const D3DBLEND_SRCCOLOR:Int=3
Const D3DBLEND_INVSRCCOLOR:Int=4
Const D3DBLEND_SRCALPHA:Int=5
Const D3DBLEND_INVSRCALPHA:Int=6
Const D3DBLEND_DESTALPHA:Int=7
Const D3DBLEND_INVDESTALPHA:Int=8
Const D3DBLEND_DESTCOLOR:Int=9
Const D3DBLEND_INVDESTCOLOR:Int=10
Const D3DBLEND_SRCALPHASAT:Int=11
Const D3DBLEND_BOTHSRCALPHA:Int=12
Const D3DBLEND_BOTHINVSRCALPHA:Int=13
Const D3DBLEND_BLENDFACTOR:Int=14
Const D3DBLEND_INVBLENDFACTOR:Int=15

'D3DTEXTUREOP
Const D3DTOP_DISABLE:Int=1
Const D3DTOP_SELECTARG1:Int=2
Const D3DTOP_SELECTARG2:Int=3
Const D3DTOP_MODULATE:Int=4
Const D3DTOP_MODULATE2X:Int=5
Const D3DTOP_MODULATE4X:Int=6
Const D3DTOP_ADD:Int=7
Const D3DTOP_ADDSIGNED:Int=8
Const D3DTOP_ADDSIGNED2X:Int=9
Const D3DTOP_SUBTRACT:Int=10
Const D3DTOP_ADDSMOOTH:Int=11
Const D3DTOP_BLENDDIFFUSEALPHA:Int=12
Const D3DTOP_BLENDTEXTUREALPHA:Int=13
Const D3DTOP_BLENDFACTORALPHA:Int=14
Const D3DTOP_BLENDTEXTUREALPHAPM:Int=15
Const D3DTOP_BLENDCURRENTALPHA:Int=16
Const D3DTOP_PREMODULATE:Int=17
Const D3DTOP_MODULATEALPHA_ADDCOLOR:Int=18
Const D3DTOP_MODULATECOLOR_ADDALPHA:Int=19
Const D3DTOP_MODULATEINVALPHA_ADDCOLOR:Int=20
Const D3DTOP_MODULATEINVCOLOR_ADDALPHA:Int=21
Const D3DTOP_BUMPENVMAP:Int=22
Const D3DTOP_BUMPENVMAPLUMINANCE:Int=23
Const D3DTOP_DOTPRODUCT3:Int=24
Const D3DTOP_MULTIPLYADD:Int=25
Const D3DTOP_LERP:Int=26

Const D3DTA_SELECTMASK:Int=$f
Const D3DTA_DIFFUSE:Int=$0
Const D3DTA_CURRENT:Int=$1
Const D3DTA_TEXTURE:Int=$2
Const D3DTA_TFACTOR:Int=$3
Const D3DTA_SPECULAR:Int=$4
Const D3DTA_TEMP:Int=$5
Const D3DTA_CONSTANT:Int=$6
Const D3DTA_COMPLEMENT:Int=$10
Const D3DTA_ALPHAREPLICATE:Int=$20

'D3DCULL
Const D3DCULL_NONE:Int=1
Const D3DCULL_CW:Int=2
Const D3DCULL_CCW:Int=3

'D3DCMPFUNC
Const D3DCMP_NEVER:Int=1
Const D3DCMP_LESS:Int=2
Const D3DCMP_EQUAL:Int=3
Const D3DCMP_LESSEQUAL:Int=4
Const D3DCMP_GREATER:Int=5
Const D3DCMP_NOTEQUAL:Int=6
Const D3DCMP_GREATEREQUAL:Int=7
Const D3DCMP_ALWAYS:Int=8

'D3DSTENCILOP
Const D3DSTENCILOP_KEEP:Int=1
Const D3DSTENCILOP_ZERO:Int=2
Const D3DSTENCILOP_REPLACE:Int=3
Const D3DSTENCILOP_INCRSAT:Int=4
Const D3DSTENCILOP_DECRSAT:Int=5
Const D3DSTENCILOP_INVERT:Int=6
Const D3DSTENCILOP_INCR:Int=7
Const D3DSTENCILOP_DECR:Int=8

'D3DFORMAT
Const D3DFMT_UNKNOWN:Int=0
Const D3DFMT_R8G8B8:Int=20
Const D3DFMT_A8R8G8B8:Int=21
Const D3DFMT_X8R8G8B8:Int=22
Const D3DFMT_R5G6B5:Int=23
Const D3DFMT_X1R5G5B5:Int=24
Const D3DFMT_A1R5G5B5:Int=25
Const D3DFMT_A4R4G4B4:Int=26
Const D3DFMT_R3G3B2:Int=27
Const D3DFMT_A8:Int=28
Const D3DFMT_A8R3G3B2:Int=29
Const D3DFMT_X4R4G4B4:Int=30
Const D3DFMT_A2B10G10R10:Int=31
Const D3DFMT_A8B8G8R8:Int=32
Const D3DFMT_X8B8G8R8:Int=33
Const D3DFMT_G16R16:Int=34
Const D3DFMT_A2R10G10B10:Int=35
Const D3DFMT_A16B16G16R16:Int=36
Const D3DFMT_D16_LOCKABLE:Int=70
Const D3DFMT_D32:Int=71
Const D3DFMT_D15S1:Int=73
Const D3DFMT_D24S8:Int=75
Const D3DFMT_D24X8:Int=77
Const D3DFMT_D24X4S4:Int=79
Const D3DFMT_D16:Int=80
Const D3DFMT_D32F_LOCKABLE:Int=82
Const D3DFMT_D24FS8:Int=83
Const D3DFMT_VERTEXDATA:Int=100
Const D3DFMT_INDEX16:Int=101
Const D3DFMT_INDEX32:Int=102

'D3DDEVTYPE
Const D3DDEVTYPE_HAL:Int=1
Const D3DDEVTYPE_REF:Int=2
Const D3DDEVTYPE_SW:Int=3

'D3DRESOURCETYPE
Const D3DRTYPE_SURFACE:Int=1
Const D3DRTYPE_VOLUME:Int=2
Const D3DRTYPE_TEXTURE:Int=3
Const D3DRTYPE_VOLUMETEXTURE:Int=4
Const D3DRTYPE_CUBETEXTURE:Int=5
Const D3DRTYPE_VERTEXBUFFER:Int=6
Const D3DRTYPE_INDEXBUFFER:Int=7

'D3DMULTISAMPLE_TYPE
Const D3DMULTISAMPLE_NONE:Int=0
Const D3DMULTISAMPLE_NONMASKABLE:Int=1
Const D3DMULTISAMPLE_2_SAMPLES:Int=2
Const D3DMULTISAMPLE_3_SAMPLES:Int=3
Const D3DMULTISAMPLE_4_SAMPLES:Int=4
Const D3DMULTISAMPLE_5_SAMPLES:Int=5
Const D3DMULTISAMPLE_6_SAMPLES:Int=6
Const D3DMULTISAMPLE_7_SAMPLES:Int=7
Const D3DMULTISAMPLE_8_SAMPLES:Int=8
Const D3DMULTISAMPLE_9_SAMPLES:Int=9
Const D3DMULTISAMPLE_10_SAMPLES:Int=10
Const D3DMULTISAMPLE_11_SAMPLES:Int=11
Const D3DMULTISAMPLE_12_SAMPLES:Int=12
Const D3DMULTISAMPLE_13_SAMPLES:Int=13
Const D3DMULTISAMPLE_14_SAMPLES:Int=14
Const D3DMULTISAMPLE_15_SAMPLES:Int=15
Const D3DMULTISAMPLE_16_SAMPLES:Int=16

'D3DSWAPEFFECT
Const D3DSWAPEFFECT_DISCARD:Int=1
Const D3DSWAPEFFECT_FLIP:Int=2
Const D3DSWAPEFFECT_COPY:Int=3

'D3DPRESENT
Const D3DPRESENT_INTERVAL_DEFAULT:Int=0
Const D3DPRESENT_INTERVAL_ONE:Int=1
Const D3DPRESENT_INTERVAL_TWO:Int=2
Const D3DPRESENT_INTERVAL_THREE:Int=4
Const D3DPRESENT_INTERVAL_FOUR:Int=8
Const D3DPRESENT_INTERVAL_IMMEDIATE:Int=$80000000

'D3DPOOL
Const D3DPOOL_DEFAULT:Int=0
Const D3DPOOL_MANAGED:Int=1
Const D3DPOOL_SYSTEMMEM:Int=2
Const D3DPOOL_SCRATCH:Int=3

'D3DBACKBUFFER_TYPE
Const D3DBACKBUFFER_TYPE_MONO:Int=0
Const D3DBACKBUFFER_TYPE_LEFT:Int=1
Const D3DBACKBUFFER_TYPE_RIGHT:Int=2

'D3DTEXTUREFILTERTYPE
Const D3DTEXF_NONE:Int=0
Const D3DTEXF_POINT:Int=1
Const D3DTEXF_LINEAR:Int=2
Const D3DTEXF_ANISOTROPIC:Int=3
Const D3DTEXF_PYRAMIDALQUAD:Int=6
Const D3DTEXF_GAUSSIANQUAD:Int=7

'D3DTRANSFORMSTATETYPE
Const D3DTS_VIEW:Int=2
Const D3DTS_PROJECTION:Int=3
Const D3DTS_TEXTURE0:Int=16
Const D3DTS_TEXTURE1:Int=17
Const D3DTS_TEXTURE2:Int=18
Const D3DTS_TEXTURE3:Int=19
Const D3DTS_TEXTURE4:Int=20
Const D3DTS_TEXTURE5:Int=21
Const D3DTS_TEXTURE6:Int=22
Const D3DTS_TEXTURE7:Int=23
Const D3DTS_WORLD:Int=256
Const D3DTS_WORLD1:Int=257
Const D3DTS_WORLD2:Int=258
Const D3DTS_WORLD3:Int=259
'D3DLIGHTTYPE
Const D3DLIGHT_POINT:Int=1
Const D3DLIGHT_SPOT:Int=2
Const D3DLIGHT_DIRECTIONAL:Int=3

'D3DRENDERSTATETYPE
Const D3DRS_TEXTUREPERSPECTIVE:Int=4	'dx7 only
Const D3DRS_ZENABLE:Int=7
Const D3DRS_FILLMODE:Int=8
Const D3DRS_SHADEMODE:Int=9
Const D3DRS_ZWRITEENABLE:Int=14
Const D3DRS_ALPHATESTENABLE:Int=15
Const D3DRS_LASTPIXEL:Int=16
Const D3DRS_SRCBLEND:Int=19
Const D3DRS_DESTBLEND:Int=20
Const D3DRS_CULLMODE:Int=22
Const D3DRS_ZFUNC:Int=23
Const D3DRS_ALPHAREF:Int=24
Const D3DRS_ALPHAFUNC:Int=25
Const D3DRS_DITHERENABLE:Int=26
Const D3DRS_ALPHABLENDENABLE:Int=27
Const D3DRS_FOGENABLE:Int=28
Const D3DRS_SPECULARENABLE:Int=29
Const D3DRS_FOGCOLOR:Int=34
Const D3DRS_FOGTABLEMODE:Int=35
Const D3DRS_FOGSTART:Int=36
Const D3DRS_FOGEND:Int=37
Const D3DRS_FOGDENSITY:Int=38
Const D3DRS_RANGEFOGENABLE:Int=48
Const D3DRS_STENCILENABLE:Int=52
Const D3DRS_STENCILFAIL:Int=53
Const D3DRS_STENCILZFAIL:Int=54
Const D3DRS_STENCILPASS:Int=55
Const D3DRS_STENCILFUNC:Int=56
Const D3DRS_STENCILREF:Int=57
Const D3DRS_STENCILMASK:Int=58
Const D3DRS_STENCILWRITEMASK:Int=59
Const D3DRS_TEXTUREFACTOR:Int=60
Const D3DRS_WRAP0:Int=128
Const D3DRS_WRAP1:Int=129
Const D3DRS_WRAP2:Int=130
Const D3DRS_WRAP3:Int=131
Const D3DRS_WRAP4:Int=132
Const D3DRS_WRAP5:Int=133
Const D3DRS_WRAP6:Int=134
Const D3DRS_WRAP7:Int=135
Const D3DRS_CLIPPING:Int=136
Const D3DRS_LIGHTING:Int=137
Const D3DRS_AMBIENT:Int=139
Const D3DRS_FOGVERTEXMODE:Int=140
Const D3DRS_COLORVERTEX:Int=141
Const D3DRS_LOCALVIEWER:Int=142
Const D3DRS_NORMALIZENORMALS:Int=143
Const D3DRS_DIFFUSEMATERIALSOURCE:Int=145
Const D3DRS_SPECULARMATERIALSOURCE:Int=146
Const D3DRS_AMBIENTMATERIALSOURCE:Int=147
Const D3DRS_EMISSIVEMATERIALSOURCE:Int=148
Const D3DRS_VERTEXBLEND:Int=151
Const D3DRS_CLIPPLANEENABLE:Int=152
Const D3DRS_POINTSIZE:Int=154
Const D3DRS_POINTSIZE_MIN:Int=155
Const D3DRS_POINTSPRITEENABLE:Int=156
Const D3DRS_POINTSCALEENABLE:Int=157
Const D3DRS_POINTSCALE_A:Int=158
Const D3DRS_POINTSCALE_B:Int=159
Const D3DRS_POINTSCALE_C:Int=160
Const D3DRS_MULTISAMPLEANTIALIAS:Int=161
Const D3DRS_MULTISAMPLEMASK:Int=162
Const D3DRS_PATCHEDGESTYLE:Int=163
Const D3DRS_DEBUGMONITORTOKEN:Int=165
Const D3DRS_POINTSIZE_MAX:Int=166
Const D3DRS_INDEXEDVERTEXBLENDENABLE:Int=167
Const D3DRS_COLORWRITEENABLE:Int=168
Const D3DRS_TWEENFACTOR:Int=170
Const D3DRS_BLENDOP:Int=171
Const D3DRS_POSITIONDEGREE:Int=172
Const D3DRS_NORMALDEGREE:Int=173
Const D3DRS_SCISSORTESTENABLE:Int=174
Const D3DRS_SLOPESCALEDEPTHBIAS:Int=175
Const D3DRS_ANTIALIASEDLINEENABLE:Int=176
Const D3DRS_MINTESSELLATIONLEVEL:Int=178
Const D3DRS_MAXTESSELLATIONLEVEL:Int=179
Const D3DRS_ADAPTIVETESS_X:Int=180
Const D3DRS_ADAPTIVETESS_Y:Int=181
Const D3DRS_ADAPTIVETESS_Z:Int=182
Const D3DRS_ADAPTIVETESS_W:Int=183
Const D3DRS_ENABLEADAPTIVETESSELLATION:Int=184
Const D3DRS_TWOSIDEDSTENCILMODE:Int=185
Const D3DRS_CCW_STENCILFAIL:Int=186
Const D3DRS_CCW_STENCILZFAIL:Int=187
Const D3DRS_CCW_STENCILPASS:Int=188
Const D3DRS_CCW_STENCILFUNC:Int=189
Const D3DRS_COLORWRITEENABLE1:Int=190
Const D3DRS_COLORWRITEENABLE2:Int=191
Const D3DRS_COLORWRITEENABLE3:Int=192
Const D3DRS_BLENDFACTOR:Int=193
Const D3DRS_SRGBWRITEENABLE:Int=194
Const D3DRS_DEPTHBIAS:Int=195
Const D3DRS_WRAP8:Int=198
Const D3DRS_WRAP9:Int=199
Const D3DRS_WRAP10:Int=200
Const D3DRS_WRAP11:Int=201
Const D3DRS_WRAP12:Int=202
Const D3DRS_WRAP13:Int=203
Const D3DRS_WRAP14:Int=204
Const D3DRS_WRAP15:Int=205
Const D3DRS_SEPARATEALPHABLENDENABLE:Int=206
Const D3DRS_SRCBLENDALPHA:Int=207
Const D3DRS_DESTBLENDALPHA:Int=208
Const D3DRS_BLENDOPALPHA:Int=209

'D3DTEXTURESTAGESTATETYPE
Const D3DTSS_COLOROP:Int=1
Const D3DTSS_COLORARG1:Int=2
Const D3DTSS_COLORARG2:Int=3
Const D3DTSS_ALPHAOP:Int=4
Const D3DTSS_ALPHAARG1:Int=5
Const D3DTSS_ALPHAARG2:Int=6
Const D3DTSS_BUMPENVMAT00:Int=7
Const D3DTSS_BUMPENVMAT01:Int=8
Const D3DTSS_BUMPENVMAT10:Int=9
Const D3DTSS_BUMPENVMAT11:Int=10
Const D3DTSS_TEXCOORDINDEX:Int=11
Const D3DTSS_ADDRESS:Int=12	'dx7 only
Const D3DTSS_MAGFILTER:Int=16 'dx7 only
Const D3DTSS_MINFILTER:Int=17 'dx7 only
Const D3DTSS_MIPFILTER:Int=18 'dx7 only
Const D3DTSS_BUMPENVLSCALE:Int=22
Const D3DTSS_BUMPENVLOFFSET:Int=23
Const D3DTSS_TEXTURETRANSFORMFLAGS:Int=24
Const D3DTSS_COLORARG0:Int=26
Const D3DTSS_ALPHAARG0:Int=27
Const D3DTSS_RESULTARG:Int=28
Const D3DTSS_CONSTANT:Int=32

'D3DSAMPLERSTATETYPE
Const D3DSAMP_ADDRESSU:Int=1
Const D3DSAMP_ADDRESSV:Int=2
Const D3DSAMP_ADDRESSW:Int=3
Const D3DSAMP_BORDERCOLOR:Int=4
Const D3DSAMP_MAGFILTER:Int=5
Const D3DSAMP_MINFILTER:Int=6
Const D3DSAMP_MIPFILTER:Int=7
Const D3DSAMP_MIPMAPLODBIAS:Int=8
Const D3DSAMP_MAXMIPLEVEL:Int=9
Const D3DSAMP_MAXANISOTROPY:Int=10
Const D3DSAMP_SRGBTEXTURE:Int=11
Const D3DSAMP_ELEMENTINDEX:Int=12
Const D3DSAMP_DMAPOFFSET:Int=13

'D3DSTATEBLOCKTYPE
Const D3DSBT_ALL:Int=1
Const D3DSBT_PIXELSTATE:Int=2
Const D3DSBT_VERTEXSTATE:Int=3

'D3DPRIMITIVETYPE
Const D3DPT_POINTLIST:Int=1
Const D3DPT_LINELIST:Int=2
Const D3DPT_LINESTRIP:Int=3
Const D3DPT_TRIANGLELIST:Int=4
Const D3DPT_TRIANGLESTRIP:Int=5
Const D3DPT_TRIANGLEFAN:Int=6

'D3DDECLUSAGE
Const D3DDECLUSAGE_POSITION:Int=0
Const D3DDECLUSAGE_BLENDWEIGHT:Int=1
Const D3DDECLUSAGE_BLENDINDICES:Int=2
Const D3DDECLUSAGE_NORMAL:Int=3
Const D3DDECLUSAGE_PSIZE:Int=4
Const D3DDECLUSAGE_TEXCOORD:Int=5
Const D3DDECLUSAGE_TANGENT:Int=6
Const D3DDECLUSAGE_BINORMAL:Int=7
Const D3DDECLUSAGE_TESSFACTOR:Int=8
Const D3DDECLUSAGE_POSITIONT:Int=9
Const D3DDECLUSAGE_COLOR:Int=10
Const D3DDECLUSAGE_FOG:Int=11
Const D3DDECLUSAGE_DEPTH:Int=12
Const D3DDECLUSAGE_SAMPLE:Int=13

'D3DDECLMETHOD
Const D3DDECLMETHOD_DEFAULT:Int=0
Const D3DDECLMETHOD_PARTIALU:Int=1
Const D3DDECLMETHOD_PARTIALV:Int=2
Const D3DDECLMETHOD_CROSSUV:Int=3
Const D3DDECLMETHOD_UV:Int=4
Const D3DDECLMETHOD_LOOKUP:Int=5
Const D3DDECLMETHOD_LOOKUPPRESAMPLED:Int=6

'D3DDECLTYPE
Const D3DDECLTYPE_FLOAT1:Int=0
Const D3DDECLTYPE_FLOAT2:Int=1
Const D3DDECLTYPE_FLOAT3:Int=2
Const D3DDECLTYPE_FLOAT4:Int=3
Const D3DDECLTYPE_D3DCOLOR:Int=4
Const D3DDECLTYPE_UBYTE4:Int=5
Const D3DDECLTYPE_SHORT2:Int=6
Const D3DDECLTYPE_SHORT4:Int=7
Const D3DDECLTYPE_UBYTE4N:Int=8
Const D3DDECLTYPE_SHORT2N:Int=9
Const D3DDECLTYPE_SHORT4N:Int=10
Const D3DDECLTYPE_USHORT2N:Int=11
Const D3DDECLTYPE_USHORT4N:Int=12
Const D3DDECLTYPE_UDEC3:Int=13
Const D3DDECLTYPE_DEC3N:Int=14
Const D3DDECLTYPE_FLOAT16_2:Int=15
Const D3DDECLTYPE_FLOAT16_4:Int=16
Const D3DDECLTYPE_UNUSED:Int=17

'D3DQUERYTYPE
Const D3DQUERYTYPE_VCACHE:Int=4
Const D3DQUERYTYPE_RESOURCEMANAGER:Int=5
Const D3DQUERYTYPE_VERTEXSTATS:Int=6
Const D3DQUERYTYPE_EVENT:Int=8
Const D3DQUERYTYPE_OCCLUSION:Int=9

Const D3DISSUE_END:Int=1
Const D3DISSUE_BEGIN:Int=2

Const D3DGETDATA_FLUSH:Int=1

Const D3DFVF_POSITION_MASK:Int=$400e
Const D3DFVF_XYZ:Int=$2
Const D3DFVF_XYZRHW:Int=$4
Const D3DFVF_XYZB1:Int=$6
Const D3DFVF_XYZB2:Int=$8
Const D3DFVF_XYZB3:Int=$a
Const D3DFVF_XYZB4:Int=$c
Const D3DFVF_XYZB5:Int=$e
Const D3DFVF_XYZW:Int=$4002
Const D3DFVF_NORMAL:Int=$10
Const D3DFVF_PSIZE:Int=$20
Const D3DFVF_DIFFUSE:Int=$40
Const D3DFVF_SPECULAR:Int=$80
Const D3DFVF_TEXCOUNT_MASK:Int=$f00
Const D3DFVF_TEXCOUNT_SHIFT:Int=8
Const D3DFVF_TEX0:Int=$000
Const D3DFVF_TEX1:Int=$100
Const D3DFVF_TEX2:Int=$200
Const D3DFVF_TEX3:Int=$300
Const D3DFVF_TEX4:Int=$400
Const D3DFVF_TEX5:Int=$500
Const D3DFVF_TEX6:Int=$600
Const D3DFVF_TEX7:Int=$700
Const D3DFVF_TEX8:Int=$800

Const D3DPRESENTFLAG_LOCKABLE_BACKBUFFER:Int=1
Const D3DPRESENTFLAG_DISCARD_DEPTHSTENCIL:Int=2
Const D3DPRESENTFLAG_DEVICECLIP:Int=4
Const D3DPRESENTFLAG_VIDEO:Int=16

Const D3DCREATE_FPU_PRESERVE:Int=$2
Const D3DCREATE_MULTITHREADED:Int=$4
Const D3DCREATE_PUREDEVICE:Int=$10
Const D3DCREATE_SOFTWARE_VERTEXPROCESSING:Int=$20
Const D3DCREATE_HARDWARE_VERTEXPROCESSING:Int=$40
Const D3DCREATE_MIXED_VERTEXPROCESSING:Int=$80
Const D3DCREATE_DISABLE_DRIVER_MANAGEMENT:Int=$100
Const D3DCREATE_ADAPTERGROUP_DEVICE:Int=$200

Const D3DCLEAR_TARGET:Int=$1
Const D3DCLEAR_ZBUFFER:Int=$2
Const D3DCLEAR_STENCIL:Int=$4

Const D3DCS_LEFT:Int=$1
Const D3DCS_RIGHT:Int=$2
Const D3DCS_TOP:Int=$4
Const D3DCS_BOTTOM:Int=$8
Const D3DCS_FRONT:Int=$10
Const D3DCS_BACK:Int=$20
Const D3DCS_PLANE0:Int=$40
Const D3DCS_PLANE1:Int=$80
Const D3DCS_PLANE2:Int=$100
Const D3DCS_PLANE3:Int=$200
Const D3DCS_PLANE4:Int=$400
Const D3DCS_PLANE5:Int=$800
Const D3DCS_ALL:Int=$fff

Const D3DCLIPSTATUS_STATUS:Int=$1
Const D3DCLIPSTATUS_EXTENTS2:Int=$2
Const D3DCLIPSTATUS_EXTENTS3:Int=$4

Const D3DSHADE_FLAT:Int=1
Const D3DSHADE_GOURAUD:Int=2
Const D3DSHADE_PHONG:Int=3

Type D3DCLIPSTATUS
	Field dwFlags:Int
	Field dwStatus:Int
	Field minx:Float,maxx:Float
	Field miny:Float,maxy:Float
	Field minz:Float,maxz:Float
End Type

Type D3DMATRIX
	Field _11#,_12#,_13#,_14#
	Field _21#,_22#,_23#,_24#
	Field _31#,_32#,_33#,_34#
	Field _41#,_42#,_43#,_44#
End Type

Extern
Struct D3DDISPLAYMODE
	Field Width:UInt
	Field Height:UInt
	Field RefreshRate:UInt
	Field Format:Int
End Struct
End Extern

Type D3DRASTER_STATUS
	Field InVBlank:Int
	Field ScanLine:Int
End Type

Struct D3DPRESENT_PARAMETERS

	Field BackBufferWidth:UInt
	Field BackBufferHeight:UInt
	Field BackBufferFormat:Int
	Field BackBufferCount:UInt

	Field MultiSampleType:Int
	Field MultiSampleQuality:UInt

	Field SwapEffect:Int
	Field hDeviceWindow:Byte Ptr
	Field Windowed:Int
	Field EnableAutoDepthStencil:Int
	Field AutoDepthStencilFormat:Int
	Field Flags:UInt

	Field FullScreen_RefreshRateInHz:UInt
	Field PresentationInterval:UInt
	
End Struct

Extern
	Function bmx_directx_D3DSURFACE_DESC_new:Byte Ptr()
	Function bmx_directx_D3DSURFACE_DESC_free(handle:Byte Ptr)
End Extern

Struct D3DSURFACE_DESC
	Field Format:Int
	Field Type_:Int
	Field Usage:Int
	Field Pool:Int
	Field MultiSampleType:Int
	Field MultiSampleQuality:Int
	Field Width:UInt
	Field Height:UInt
End Struct

Type D3DLOCKED_RECT
	Field Pitch:Int
	Field pBits:Byte Ptr
End Type

Type D3DRECTPATCH_INFO
	Field StartVertexOffsetWidth:Int
	Field StartVertexOffsetHeight:Int
	Field Width:Int
	Field Height:Int
	Field Stride:Int
	Field Basis:Int
	Field Degree:Int
End Type

Type D3DTRIPATCH_INFO
	Field StartVertexOffset:Int
	Field NumVertices:Int
	Field Basis:Int
	Field Degree:Int
End Type
